#!/bin/bash

declare -A HOSTS
HOSTS[temp]='192.168.0.41:5000'
HOSTS[leds]='192.168.0.41:5101'
HOSTS[sunset]='https://api.sunrise-sunset.org/json'

SENSOR='000006962d0f'
HOUR=`date +%H`

declare -A WEATHER
WEATHER[vHot]='255,0,0'
WEATHER[hot]='199,55,25'
WEATHER[normal]='165,184,108'
WEATHER[cold]='35,7,247'
WEATHER[vCold]='35,7,247'

declare -A LONGLAT
LONGLAT[lat]=50.832291
LONGLAT[long]=0.318620

NOW=`date +%s`



# TESTMODE sunset not met
if [ -f TESTMODE1 ]; then
    HOSTS[sunset]='localhost:4444'
    NOW=1635525643
    HOUR=16
fi

# TESTMODE sunset met and is the evening
if [ -f TESTMODE2 ]; then
    HOSTS[sunset]='localhost:4444'
    NOW=1635527503
    HOUR=16
fi

# TESTMODE sunset met and is in the early morning
if [ -f TESTMODE3 ]; then
    HOSTS[sunset]='localhost:4444'
    NOW=1635527503
    HOUR=1
fi