#!/bin/bash
# returns true if it is past sunset
# TODO - add an offset argument

. config

NOW=`date +%s`
resp=`curl -s "https://api.sunrise-sunset.org/json?lat=${LONGLAT[lat]}&lng=${LONGLAT[long]}&formatted=0" |jq -r .results.sunset`
SUNSET=`date -d $resp +%s`

if [ $NOW -gt $SUNSET ]
then
    ret=1
else
    ret=0
fi

echo $ret
exit $ret