#!/bin/bash
# returns true if it is past sunset
# arg 1 is + offset in minutes


. config
if [ $1 ]
then
    OFFSET=`expr $1 \* 60`
else
    OFFSET=0
fi

resp=`curl -m2  -s -k "${HOSTS[sunset]}?lat=${LONGLAT[lat]}&lng=${LONGLAT[long]}&formatted=0" |jq -r .results.sunset`
if [ $resp ]; then
    SUNSET=`date -d $resp +%s`
    TRIGGER=`expr $SUNSET + $OFFSET`
    
    # echo $NOW
    # echo $TRIGGER
    
    if [ $NOW -gt $TRIGGER ]
    then
        ret=1
    else
        ret=0
    fi
    
else
    ret=-1
fi

echo $ret
exit $ret
